apps/loginandreg/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='homepage'),
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    url(r'^register/user$', register_user, name='register_user'),
    url(r'^login/user$', login_user, name='login_user'),
]

apps/soundcloud/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^stream$', index, name='stream'),
    url(r'^logout$', logout, name='logout'),
    url(r'^update_profile/(?P<id>\d+)$', update_profile, name='update_profile'),
    url(r'^user/(?P<id>\d+)$', user, name='user'),
    url(r'^song/(?P<id>\d+)$', song, name='song'),
    url(r'^follow$', follow, name='follow'),
    url(r'^unfollow$', unfollow, name='unfollow'),
    url(r'^search$', search, name='search'),
    url(r'^stream/addcomment$', create_comment, name='addcomment'),
    url(r'^stream/deletecomment$', delete_comment, name='deletecomment'),
    url(r'^like$', like, name='like'),
    url(r'^unlike$', unlike, name='unlike'),
    url(r'^artist_info/(?P<name>[\w.@+-]+)$', artist_info, name='artist_info'),
]

apps/upload/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^create$', create, name='create'),
    url(r'^add_playlist/(?P<id>\d+)$', add_playlist, name='add_playlist'),
    url(r'^create_playlist$', create_playlist, name='create_playlist'),
    url(r'^delete_playlist_song/(?P<id>\d+)$', delete_playlist_song, name='delete_playlist_song'),
    url(r'^playlist_info/(?P<id>\d+)$', playlist_info, name='playlist_info'),
    url(r'^repost/(?P<id>\d+)$', repost, name='repost'),
    url(r'^remove_repost/(?P<id>\d+)$', remove_repost, name='remove_repost'),
]

soundcloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.loginandreg.urls', namespace='loginandreg')),
    url(r'^soundspace/', include('apps.soundcloud.urls', namespace='soundspace')),
    url(r'^upload/', include('apps.upload.urls', namespace='upload')),
]

apps/soundcloud/models.py
from __future__ import unicode_literals
from ..upload.models import Song
from ..loginandreg.models import User
from django.db import models

class Comment(models.Model):
    user = models.ForeignKey(User)
    song = models.ForeignKey(Song)
    comment = models.TextField(max_length=500, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class RelationshipManager(models.Manager):
    def follow(self, info, **kwargs):
        following = User.objects.get(id=info['followingid'])
        follower = User.objects.get(id=info['followerid'])
        Relationship.objects.get_or_create(following=following, follower=follower)
        return {'success': 'Followed!'}

    def unfollow(self, info, **kwargs):
        unfollow = User.objects.get(id=info['unfollowid'])
        follower = User.objects.get(id=info['followerid'])
        try:
            Relationship.objects.get(following=unfollow, follower=follower).delete()
        except:
            pass
        return {'success': 'Unfollowed!'}

class Relationship(models.Model):
    following = models.ForeignKey(User, related_name='user_following')
    follower = models.ForeignKey(User, related_name='user_followers')
    created_at = models.DateTimeField(auto_now_add=True)
    objects = RelationshipManager()

class LikeManager(models.Manager):
    def create_like(self, info, userid, **kwargs):
        user = User.objects.get(id=userid)
        song = Song.objects.get(id=info['song_id'])
        like, created = Like.objects.get_or_create(song=song, user=user)
        return {'success': 'Liked!'}

    def unlike(self, info, userid, **kwargs):
        user = User.objects.get(id=userid)
        song = Song.objects.get(id=info['song_id'])
        try:
            Like.objects.get(song=song, user=user).delete()
            return {'success': 'Unliked!'}
        except:
            pass

class Like(models.Model):
    song = models.ForeignKey(Song, related_name='liked_song')
    user = models.ForeignKey(User, related_name='liked_user')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = LikeManager()

apps/soundcloud/forms.py
from django import forms
from ..loginandreg.models import User
from ..upload.models import *
from .models import Comment
from django.utils.translation import ugettext_lazy as _

class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['name', 'genre', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 1, 'cols': 20})
          }
        labels = {
            'comment':_(''),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 2, 'cols': 40})
          }
        labels = {
            'comment':_(''),
        }

class UpdateForm(forms.Form):
    GENDER_CHOICES = (
            ('', '--------'),
            ('M', 'Male'),
            ('F', 'Female'),
            ('O', 'Other')
        )

    name = forms.CharField(required=False, max_length=45)
    picture = forms.FileField(required=False)
    email = forms.CharField(required=False)
    age = forms.IntegerField(required=False)
    gender = forms.ChoiceField(required=False, choices=GENDER_CHOICES)
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 2, 'cols': 20}))
    new_password = forms.CharField(required=False, widget=forms.PasswordInput())
    confirm_current_password = forms.CharField(required=True, widget=forms.PasswordInput())

apps/soundcloud/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from ..upload.models import *
from ..loginandreg.models import *
from .models import *
from .forms import *
from .utils import *

QUERY="search-query"

MODEL_MAP = {
    Song: ["title","genre","artist","description"],
    }

def index(request):
    playlists= Playlist.objects.filter(user_id=request.session['user_id'])
    logged_on_user = User.objects.get(id=request.session['user_id'])
    likes = Like.objects.filter(user=logged_on_user)
    user_likes = {}
    for l in likes:
        if l.user_id == request.session['user_id']:
            user_likes[l.song_id] = True
    context = {
        'logged_on_user': logged_on_user,
        'commentForm': CommentForm(),
        'all_songs': Song.objects.all().order_by('-created_at'),
        'comments': Comment.objects.all(),
        'user_liked': user_likes,
        'playlists':playlists,
    }
    return render(request, 'soundcloud/index.html', context)

def logout(request):
    if request.method == 'POST':
        request.session.clear()
    return redirect(reverse('loginandreg:homepage'))

def song(request, id):
    logged_on_user = User.objects.get(id=request.session['user_id'])
    likes = Like.objects.filter(user=logged_on_user)
    user_likes = {}
    for l in likes:
        if l.user_id == request.session['user_id']:
            user_likes[l.song_id] = True
    context = {
        'commentForm': CommentForm(),
        'song': Song.objects.get(id=id),
        'user_liked': user_likes,
        'comments': Comment.objects.all(),
    }
    return render(request, 'soundcloud/song.html', context)

def user(request, id):
    profile_user = User.objects.get(id=id)
    logged_on_user = User.objects.get(id=request.session['user_id'])
    playlists= Playlist.objects.filter(user_id=id)
    all_songs= Song.objects.filter(user=profile_user).order_by('-created_at')
    num_followers= len(Relationship.objects.filter(following=profile_user))
    num_following= len(Relationship.objects.filter(follower=profile_user))
    user_follows= Relationship.objects.filter(following=profile_user).all().order_by('-id')[:5]
    user_followings=Relationship.objects.filter(follower=profile_user).all().order_by('-id')[:5]
    for song in all_songs:
        reposts = song.song_reposts.all()
        for repost in reposts:
            user= repost.user_id
            if profile_user.id == user:
                song.joined=True
            else:
                song.joined=False
    likes = Like.objects.filter(user=logged_on_user)
    user_likes = {}
    for l in likes:
        if l.user_id == request.session['user_id']:
            user_likes[l.song_id] = True
    context = {
            'reposts':Repost.objects.filter(user_id=id),
            'playlists':playlists,
            'profile_user': profile_user,
            'commentForm': CommentForm(),
            'playlistForm': PlaylistForm(),
            'num_followers': num_followers,
            'num_following': num_following,
            'all_songs': all_songs,
            'user_liked': user_likes,
            'user_follows':user_follows,
            'user_followings':user_followings,
            'comments': Comment.objects.all(),
            'following': Relationship.objects.filter(follower=logged_on_user, following=profile_user),
            }
    return render(request, 'soundcloud/userinfo.html', context)


def update_profile(request, id):
    user = User.objects.get(id=id)
    context={
        'user':user,
        'updateForm': UpdateForm(),
    }
    if request.method == 'POST':
        User.objects.update_user(request.POST, request.FILES)
        request.session['username'] = request.POST['name']
        return redirect(reverse('soundspace:update_profile', kwargs={'id':id}))
    return render(request, 'soundcloud/updateinfo.html', context)

def create_comment(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.session['user_id'])
        song = Song.objects.get(id=request.POST['song_id'])
        Comment.objects.create(user=user, song=song, comment=request.POST['comment'])
        return redirect(reverse('soundspace:stream'))

def delete_comment(request):
    if request.method == 'POST':
        Comment.objects.get(id=request.POST['comment_id']).delete()
        return redirect(reverse('soundspace:stream'))

def follow(request):
    if request.method == 'POST':
        profile_user_id = request.POST['followingid']
        response = Relationship.objects.follow(request.POST)
        return redirect(reverse('soundspace:user', kwargs={'id':profile_user_id}))

def unfollow(request):
    if request.method == 'POST':
        profile_user_id = request.POST['unfollowid']
        response = Relationship.objects.unfollow(request.POST)
        return redirect(reverse('soundspace:user', kwargs={'id':profile_user_id}))

def like(request):
    if request.method == 'POST':
        user_id = request.session['user_id']
        Like.objects.create_like(request.POST, user_id)
        return redirect(reverse('soundspace:stream'))

def unlike(request):
    if request.method == 'POST':
        user_id = request.session['user_id']
        Like.objects.unlike(request.POST, user_id)
        return redirect(reverse('soundspace:stream'))

def search(request):
    playlists= Playlist.objects.filter(user_id=request.session['user_id'])
    logged_on_user = User.objects.get(id=request.session['user_id'])
    likes = Like.objects.filter(user=logged_on_user)
    user_likes = {}
    for l in likes:
        if l.user_id == request.session['user_id']:
            user_likes[l.song_id] = True
    query_string = ''
    all_songs = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        song_query = get_query(query_string, ['artist','description','genre','title'])
        all_songs = Song.objects.filter(song_query).order_by('-title')
    context={
        'query_string': query_string,
        'all_songs': all_songs,
        'commentForm': CommentForm(),
        'comments': Comment.objects.all(),
        'user_liked': user_likes,
        'playlists':playlists,
    }
    return render(request, 'soundcloud/search.html', context)

def artist_info(request, name):
    playlists= Playlist.objects.filter(user_id=request.session['user_id'])
    songs=Song.objects.filter(artist__iexact=name)
    logged_on_user = User.objects.get(id=request.session['user_id'])
    likes = Like.objects.filter(user=logged_on_user)
    user_likes = {}
    for l in likes:
        if l.user_id == request.session['user_id']:
            user_likes[l.song_id] = True
    context={
        'songs':songs,
        'name':name,
        'commentForm': CommentForm(),
        'comments': Comment.objects.all(),
        'user_likeS': user_likes,
        'playlists':playlists,
    }
    return render(request, 'soundcloud/artist.html', context)

apps/soundcloud/templates/soundcloud/userinfo.html
<!DOCTYPE html>
{% load static %}
{% load social_widgets %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Profile Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'soundcloud/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'soundcloud/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'soundcloud/css/jumbotron.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'soundcloud/js/ie-emulation-modes-warning.js' %}"></script>

  </head>
  <body>
    <div id="fb-root"></div>
    <script>
      (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>

    <nav class="navbar navbar-light bg-faded navbar-fixed-top" style="background-color: #d3d3d3;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'loginandreg:homepage' %}"><img src='{% static 'loginandreg/image/soundspace.png' %}'></a>
          <a class="navbar-brand" href="{% url 'soundspace:stream' %}">Home</a>
          <a class="navbar-brand" href="{% url 'upload:index' %}">Upload!</a>
          <a class="navbar-brand searchbar">
            <form method="get" action="{% url 'soundspace:search' %}">
              <label for="id_q">Search:</label>
              <input type="text" name="q" id="id_q"/>
              <input type="submit" value=""/>
            </form>
          </a>
          <a class="navbar-brand dropdown-toggle" type="button" data-toggle="dropdown"> {{request.session.username}}
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'soundspace:update_profile' id=request.session.user_id %}">Edit Profile</a></li>
            <li><a href="{% url 'soundspace:user' id=request.session.user_id %}">Profile</a></li>
          </ul>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" action='{% url 'soundspace:logout' %}' method='POST'>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Sign Out</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    <div class="jumbotron">
      <div class="container">
        <div class='profile'>
          {% if messages %}
            {% for message in messages %}
              {{message}}
            {% endfor %}
          {% endif %}
          <h2>{{profile_user.name}}</h2>
          {% if profile_user.image %}
            <img class='profilepic' src='{% static 'soundcloud/' %}{{profile_user.image}}' alt='Profile Picture'>
          {% endif %}
          {{profile_user.description}}
        </div>

        <div class='followbox'>
          {% if not following %}
          <div class='follow'>
            <form action='{% url 'soundspace:follow' %}' method='POST'>
            {% csrf_token %}
              <input hidden name='followerid' value='{{request.session.user_id}}'>
              <input hidden name='followingid' value='{{profile_user.id}}'>
              <input type='submit' name='follow' value=''>
            </form>
          </div>
          <br>
          {% elif following %}
          <div class='unfollow'>
            <form action='{% url 'soundspace:unfollow' %}' method='POST'>
            {% csrf_token %}
              <input hidden name='followerid' value='{{request.session.user_id}}'>
              <input hidden name='unfollowid' value='{{profile_user.id}}'>
              <input type='submit' name='unfollow' value=''>
            </form>
          </div>
          {% endif %}
          <br>
          <p>Followers: {{num_followers}}</p>
          {% for user_follower in user_follows %}
          <a href="{% url 'soundspace:user' id=user_follower.follower.id %}">{{user_follower.follower.name}}</a>
          {% endfor %}
          <p>Following: {{num_following}}</p>
          {% for user_following in user_followings %}
          <a href="{% url 'soundspace:user' id=user_following.following.id %}">{{user_following.following.name}}</a>
          {% endfor %}
          <br>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <h3>Tracks</h3>
          {% for song in all_songs %}
          <div class='song-image'>
            <img class='song-cover' src='{% static 'soundcloud/' %}{{song.cover_image}}' alt='Song Cover'>
          </div>
          <div class='song-info'>
            <a href='{% url 'soundspace:song' id=song.id %}'><span class='song-title'>{{song.title}}</a> - <a href="{% url 'soundspace:artist_info' name=song.artist %}">{{song.artist}}</a></span>
            <p>Posted by: <a href='{% url 'soundspace:user' id=song.user.id %}'>{{song.user.name}}</a> {{song.created_at|date:"M d H:i"}}</p>
            {% social_widget_render "twitter/share_button.html" href="" %}<br>
            <div class="fb-share-button" data-href="http://127.0.0.1:8000/soundspace/{{song.id}}" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a></div>

          </div>
            <audio id="music" preload="true">
              <source src="{% static 'soundcloud/' %}{{song.song}}">
            </audio>
            <div id="audioplayer">
              <button id="pButton" class="play"></button>
              <div id="timeline">
                <div id="playhead"></div>
              </div>
            </div>
            <div class='activitybar'>
            {% if song.id in user_liked %}
            <div class='unlikebtn'>
            <form action="{% url 'soundspace:unlike' %}" method="post">
            {% csrf_token %}
              <input hidden name='song_id' value='{{song.id}}'>
              <input class='unlike'type="submit" value="" />
            </form>
          </div>
          {% else %}
          <div class='likebtn'>
          <form action="{% url 'soundspace:like' %}" method="post">
            {% csrf_token %}
            <input hidden name='song_id' value='{{song.id}}'>
            <input type="submit" value="" />
          </form>
          </div>
          {% endif %}
          <div class='repost'>
            <form class="" action="{% url 'upload:repost' id=song.id %}" method="post">
              {% csrf_token %}
              <input type="submit" name="" value="">
            </form>
          </div>
          <div class='playlist'>
            <form class="" action="{% url 'upload:add_playlist' id=song.id %}" method="post">
              {% csrf_token %}
              <input type="submit" name="add" value="">
              <select class="" name="playlist_id">
                {% for playlist in playlists %}
                  <option value="{{playlist.id}}">{{playlist.name}}</option>
                {% endfor %}
              </select>
            </form>
          </div>
          <br>
        </div>
          <br>
        <div class='commentbox'>
          <form action="{% url 'soundspace:addcomment' %}" method="post">
            {% csrf_token %}
            {% if logged_on_user.image %}
              <img class='commentprofilepic' src='{% static 'soundcloud/' %}{{logged_on_user.image}}' alt='Profile Picture'>
            {% endif %}
            {{commentForm}}
            <input hidden name='song_id' value='{{song.id}}'>
            <input type="submit" value="" />
          </form>
        </div>
            {% for comment in comments %}
              {% if comment.song.id == song.id %}
              <div class='bigcommentbox'>
                <div class="comment-user-img">
                  <img class='commentuserpic' src='{% static 'soundcloud/' %}{{comment.user.image}}'>
                </div>
                <div class='comment'>
                <a href='{% url 'soundspace:user' id=comment.user.id %}'><p>{{comment.user.name}}</a> at {{comment.created_at|date:"M d H:i"}}</p>
                {{comment.comment}}
                {% if comment.user.id == request.session.user_id %}
                <form action="{% url 'soundspace:deletecomment' %}" method="post">
                  {% csrf_token %}
                  <input hidden name='comment_id' value='{{comment.id}}'>
                  <input type="submit" value="" />
                </form>
                {% endif %}
                </div>
              </div>
              {% endif %}
          {% endfor %}
          <br><br>
          {% endfor %}
        </div>
        <div class="col-md-3">
          <h3>Playlists:</h3>
          {% for playlist in playlists%}
            <p><a href="{% url 'upload:playlist_info' id=playlist.id %}">{{playlist.name}}</a></p>
          {% endfor %}
          <br>
          <form class="" action="{% url 'upload:create_playlist' %}" method="post">
            {% csrf_token %}
            {{playlistForm.as_p}}
            <input type="submit" name="" value="Create a playlist">
          </form>

        </div>

        <div class="col-md-3">
          <h3>Reposts:</h3>
          {% for repost in reposts %}
          <a href='{% url 'soundspace:song' id=repost.post.id %}'>{{repost.post.title}}</a> - {{repost.post.artist}}
          <audio id="music" preload="true">
            <source src="{% static 'soundcloud/' %}{{repost.post.song}}">
          </audio>
          <div id="audioplayer">
            <button id="pButton" class="play"></button>
            <div id="timeline">
              <div id="playhead"></div>
            </div>
          </div>

          {% if repost.user.id == request.session.user_id %}
            <div class='repost'>
            <form class="" action="{% url 'upload:remove_repost' id=repost.post.id %}" method="post">
              {% csrf_token %}
              <input type="submit" name="" value="">
            </form>
            </div>
          {% endif %}
        {% endfor %}
        </div>
        </div>

      <hr>

      <footer>

      </footer>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'soundcloud/js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'soundcloud/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'soundcloud/js/musicplayer.js'%}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'soundcloud/js/ie10-viewport-bug-workaround.js'%}"></script>
  </body>
</html>