apps/loginandreg/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='homepage'),
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    url(r'^register/user$', register_user, name='register_user'),
    url(r'^login/user$', login_user, name='login_user'),
]

soundcloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.loginandreg.urls', namespace='loginandreg')),
    url(r'^soundspace/', include('apps.soundcloud.urls', namespace='soundspace')),
    url(r'^upload/', include('apps.upload.urls', namespace='upload')),
]

apps/loginandreg/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
import bcrypt
import datetime

onlyLetters = RegexValidator(r'^[a-zA-Z ]+$', message='Must be letters only.')
def validateLengthGreaterThanTwo(value):
    if len(value) < 3:
        raise ValidationError('Must be longer than 2 characters'.format(value))

class UserManager(models.Manager):
    def login(self, object):
        email = object['email']
        password = object['password']
        try:
            user = User.objects.get(email=email)
            pw_hash = bcrypt.hashpw(password.encode(), user.password.encode())
            if pw_hash == user.password:
                return {'username': user.name, 'uid': user.id}
        except:
            return {'error': 'Username/Password does not match.'}

    def register(self, object, **kwargs):
        name = object['name']
        email = object['email']
        password = object['password']
        age = object['age']
        gender = object['gender']
        pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        User.objects.create(name=name, email=email, password=pw_hash, age=age, gender=gender)
        user = User.objects.get(email=email)
        return {'uid': user.id, 'user_name':user.name}

    def update_user(self, info, files, **kwargs):
        confirm = info['confirm_current_password']
        new_password = info['new_password']
        new_pw_hash = bcrypt.hashpw(new_password.encode(), bcrypt.gensalt())
        user = User.objects.get(id=info['updateid'])

        try:
            pw_hash = bcrypt.hashpw(confirm.encode(), user.password.encode())
            if pw_hash == user.password:
                try:
                    user.name = info['name']
                    user.gender = info['gender']
                    user.email = info['email']
                    user.password = new_pw_hash
                    user.age = info['age']
                    user.image= files['picture']
                    user.description = info['description']
                    user.save()
                    return {'success': 'User information has been updated!'}
                except:
                    return {'error': 'ERROR'}
        except:
            return {'error': 'Username/Password does not match.'}

class User(models.Model):
    GENDER_CHOICES = (
            ('M', 'Male'),
            ('F', 'Female'),
            ('O', 'Other')
        )
    name = models.CharField(max_length=55, validators=[validateLengthGreaterThanTwo, onlyLetters])
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    email = models.EmailField(null=True)
    password = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    image = models.FileField(upload_to='profileimage', default='profileimage/default-profile-picture.jpeg')
    description= models.TextField(max_length=2000, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/loginandreg/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError 
from django.utils.translation import ugettext_lazy as _

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'age', 'gender']
    password = forms.CharField(min_length=8, max_length=100, widget=forms.PasswordInput)
    confirm_password = forms.CharField(min_length=8, max_length=100, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError('Passwords do not match!')

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(min_length=8, max_length=100, widget=forms.PasswordInput)

apps/loginandreg/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from .models import User

def index(request):
    if 'user_id' in request.session:
        return redirect(reverse('soundspace:stream'))
    return render(request, 'loginandreg/index.html')

def login(request):
    context = {
        'loginForm': LoginForm()
    }
    if 'user_id' in request.session:
        return redirect(reverse('soundspace:stream'))
    return render(request, 'loginandreg/login.html', context)

def register(request):
    context = {
        'regForm': RegisterForm()
    }
    if 'user_id' in request.session:
        return redirect(reverse('soundspace:stream'))
    return render(request, 'loginandreg/register.html', context)

def register_user(request):
    if request.method == 'POST':
        regForm = RegisterForm(request.POST)
        messages.add_message(request, messages.ERROR, regForm.errors)
        if regForm.is_valid():
            response = User.objects.register(request.POST)
            request.session['username'] = response['user_name']
            request.session['user_id'] = response['uid']
            return redirect(reverse('soundspace:stream'))
        else:
            return redirect(reverse('loginandreg:register'))

def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            response = User.objects.login(request.POST)
            if 'error' in response:
                messages.add_message(request, messages.ERROR, 'Username/Password does not match')
                return redirect(reverse('loginandreg:login'))
            else:
                user=User.objects.get(email=request.POST['email'])
                request.session['username'] = user.name
                request.session['user_id'] = user.id
                return redirect(reverse('soundspace:stream'))

apps/loginandreg/templates/loginandreg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SoundSpace</title>
  </head>
  <body>

  </body>
</html>

apps/loginandreg/templates/loginandreg/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Soundspace Login</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'loginandreg/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'loginandreg/css/login.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'loginandreg/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'loginandreg/css/starter-template.css' %}" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'loginandreg/css/style.css' %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'loginandreg/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-light navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'loginandreg:homepage' %}"><img src='{% static 'loginandreg/image/soundspace.png' %}' alt='SoundSpace Logo'></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'loginandreg:login' %}">Log In</a></li>
            <li><a href="{% url 'loginandreg:register' %}">Sign Up</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">

      <div class="starter-template">
        {% if messages %}
          {% for m in messages %}
            <div id="messages"><p>{{m}}</p></div>
          {% endfor %}
        {% endif %}
        <form action='{% url 'loginandreg:login_user' %}' method='POST'>
          {% csrf_token %}
          {{loginForm.as_p}}
          <input type='submit' name='login' value='Log In'>
        </form>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'loginandreg/js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'loginandreg/js/template.js' %}"></script>
    <script src="{% static 'loginandreg/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'loginandreg/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

apps/loginandreg/templates/loginandreg/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Soundspace Registration</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'loginandreg/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'loginandreg/css/login.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'loginandreg/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'loginandreg/css/starter-template.css' %}" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'loginandreg/css/style.css' %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'loginandreg/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-light navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'loginandreg:homepage' %}"><img src='{% static 'loginandreg/image/soundspace.png' %}' alt='SoundSpace Logo'></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'loginandreg:login' %}">Log In</a></li>
            <li><a href="{% url 'loginandreg:register' %}">Sign Up</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">

      <div class="starter-template">
        {% if messages %}
          {% for m in messages %}
            <div id="messages">{{m}}</div>
          {% endfor %}
        {% endif %}
        <p>If you have an account, sign in <a href='{% url 'loginandreg:login' %}'>here.</a></p>
        <form action='{% url 'loginandreg:register_user' %}' method='POST'>
          {% csrf_token %}
          {{regForm.as_p}}
          <input type='submit' name='register' value='Register'>
        </form>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'loginandreg/js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'loginandreg/js/template.js' %}"></script>
    <script src="{% static 'loginandreg/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'loginandreg/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>