apps/loginandreg/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='homepage'),
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    url(r'^register/user$', register_user, name='register_user'),
    url(r'^login/user$', login_user, name='login_user'),
]

apps/soundcloud/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^stream$', index, name='stream'),
    url(r'^logout$', logout, name='logout'),
    url(r'^update_profile/(?P<id>\d+)$', update_profile, name='update_profile'),
    url(r'^user/(?P<id>\d+)$', user, name='user'),
    url(r'^song/(?P<id>\d+)$', song, name='song'),
    url(r'^follow$', follow, name='follow'),
    url(r'^unfollow$', unfollow, name='unfollow'),
    url(r'^search$', search, name='search'),
    url(r'^stream/addcomment$', create_comment, name='addcomment'),
    url(r'^stream/deletecomment$', delete_comment, name='deletecomment'),
    url(r'^like$', like, name='like'),
    url(r'^unlike$', unlike, name='unlike'),
    url(r'^artist_info/(?P<name>[\w.@+-]+)$', artist_info, name='artist_info'),
]

apps/upload/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^create$', create, name='create'),
    url(r'^add_playlist/(?P<id>\d+)$', add_playlist, name='add_playlist'),
    url(r'^create_playlist$', create_playlist, name='create_playlist'),
    url(r'^delete_playlist_song/(?P<id>\d+)$', delete_playlist_song, name='delete_playlist_song'),
    url(r'^playlist_info/(?P<id>\d+)$', playlist_info, name='playlist_info'),
    url(r'^repost/(?P<id>\d+)$', repost, name='repost'),
    url(r'^remove_repost/(?P<id>\d+)$', remove_repost, name='remove_repost'),
]

soundcloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.loginandreg.urls', namespace='loginandreg')),
    url(r'^soundspace/', include('apps.soundcloud.urls', namespace='soundspace')),
    url(r'^upload/', include('apps.upload.urls', namespace='upload')),
]

apps/upload/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginandreg.models import User

class Song(models.Model):
    user = models.ForeignKey(User, null=True)
    description = models.TextField(max_length=255, blank=True)
    genre = models.CharField(max_length=45)
    title = models.CharField(max_length=45)
    artist = models.CharField(max_length=45)
    tags = models.ManyToManyField('Tag', related_name='songs', blank=True)
    cover_image = models.FileField(upload_to='album_images', default='images/nosong.png', null=False)
    song = models.FileField(upload_to='songs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name= models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Playlist(models.Model):
    name = models.CharField(max_length=45)
    genre = models.CharField(max_length=45, null=True )
    description = models.TextField(max_length=45, null=True)
    songs = models.ManyToManyField(Song, related_name="song_playlists")
    user= models.ForeignKey(User, related_name="user_playlists")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Repost(models.Model):
    post= models.ForeignKey(Song, related_name='song_reposts')
    user= models.ForeignKey(User, related_name='user_reposts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/upload/forms.py
from django import forms
from .models import Song

GENRE_CHOICES = (
    ('Alternative Rock', 'Alternative Rock'),
    ('Ambient', 'Ambient'),
    ('Classical', 'Classical'),
    ('Country', 'Country'),
    ('Comedy', 'Comedy'),
    ('Dance/EDM', 'Dance/EDM'),
    ('Drum & Bass', 'Drum & Bass'),
    ('Dubstep', 'Dubstep'),
    ('Electronic', 'Electronic'),
    ('Folk', 'Folk'),
    ('Hip Hop & Rap', 'Hip Hop & Rap'),
    ('House', 'House'),
    ('Indie', 'Indie'),
    ('Latin', 'Latin'),
    ('Metal', 'Metal'),
    ('Piano', 'Piano'),
    ('R&B & Soul', 'R&B & Soul'),
    ('Rock', 'Rock'),
    ('Soundtrack', 'Soundtrack'),
    ('Techno', 'Techno'),
    ('Trance', 'Trance'),
    ('Trap', 'Trap'),
    ('World', 'World'),
)

class DocumentForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ('song', 'title', 'artist', 'description', 'tags', 'cover_image')
        labels = {

        }
        widgets = {
            'description': forms.Textarea(attrs={'rows': 2, 'cols': 40}),
            'tags': forms.Textarea(attrs={'rows': 1, 'cols': 40})
          }
    genre = forms.ChoiceField(choices=GENRE_CHOICES, required=False)

apps/upload/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.urlresolvers import reverse
from django.contrib import messages
from ..loginandreg.models import User

from .models import *
from .forms import DocumentForm

def index(request):
    documents = Song.objects.all()
    context = {
        'docForm': DocumentForm()
    }
    return render(request, "upload/index.html", context)

def create(request):
    user = User.objects.get(id=request.session['user_id'])
    song = request.FILES['song']
    cover_image = request.FILES.get('cover_image', 'images/nosong.png')
    new = Song.objects.create(user=user, artist=request.POST['artist'], description = request.POST['description'] , genre= request.POST['genre'] , title= request.POST['title'], cover_image=cover_image , song= request.FILES['song'], )
    added_tags= request.POST['tags']
    all_tags= added_tags.split(',')
    for new_tag in all_tags:
        tag, created = Tag.objects.get_or_create(name=new_tag.lower().strip())
        new.tags.add(tag)
    messages.warning(request, "Thanks for your contribution!")
    return redirect(reverse('upload:index'))

def add_playlist(request, id):

    song=Song.objects.get(id=id)
    try:
        user= User.objects.get(id=request.session['user_id'])
        playlist= user.user_playlists.get(id=request.POST['playlist_id'])

        playlist.songs.add(song)

        return redirect(reverse('upload:playlist_info', kwargs={'id':request.POST['playlist_id']}))
    except:
        playlist_id = request.POST.get('playlist_id', False)
        if playlist_id == False:
            messages.warning(request, "**Please create a playlist to add to!**")
            return redirect(reverse('soundspace:user', kwargs={'id':request.session['user_id']}))
        return redirect(reverse('upload:playlist_info', kwargs={'id':request.POST['playlist_id']}))

def create_playlist(request):
    user = User.objects.get(id=request.session['user_id'])
    Playlist.objects.create(name=request.POST['name'], genre= request.POST['genre'], description=request.POST['description'], user=user)
    return redirect(reverse('soundspace:user', kwargs={'id':request.session['user_id']}))

def delete_playlist_song(request, id):
    select=request.POST['playlist_id']
    playlist = Playlist.objects.get(id=select)
    song = Song.objects.get(id=id)
    playlist.songs.remove(song)
    return redirect(reverse('soundspace:user', kwargs={'id':request.session['user_id']}))

def playlist_info(request, id):
    playlist = Playlist.objects.get(id=id)
    songs=playlist.songs.all()
    user=playlist.user
    context={
        'user': user,
        'songs': songs,
        'playlist':playlist
    }
    if playlist.user_id != request.session['user_id']:
        return redirect(reverse('soundspace:user', kwargs={'id':request.session['user_id']}))
    return render(request, 'soundcloud/playlist.html', context)

def repost(request,id):
    try:
        Repost.objects.get(post_id=id, user_id=request.session['user_id'])
    except:
        Repost.objects.create(post_id=id,user_id=request.session['user_id'])
    return redirect(reverse('soundspace:user', kwargs={'id':request.session['user_id']}))

def remove_repost(request, id):
    user_repost= Repost.objects.get(user_id=request.session['user_id'], post_id=id).delete()
    return redirect(reverse('soundspace:user', kwargs={'id':request.session['user_id']}))

apps/upload/templates/upload/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Upload your music and audio on Soundspace</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'soundcloud/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'soundcloud/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'soundcloud/css/jumbotron.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'soundcloud/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-light bg-faded navbar-fixed-top" style="background-color: #d3d3d3;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'loginandreg:homepage' %}"><img src='{% static 'loginandreg/image/soundspace.png' %}'></a>
          <a class="navbar-brand" href="{% url 'soundspace:stream' %}">Home</a>
          <a class="navbar-brand" href="{% url 'upload:index' %}">Upload a Song!</a>
          <a class="navbar-brand">
            <form method="get" action="{% url 'soundspace:search' %}">
              <label for="id_q">Search:</label>
              <input type="text" name="q" id="id_q"/>
              <input type="submit" value="Submit"/>
            </form>
          </a>
        </div>
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">{{request.session.username}}
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <li><a href="{% url 'soundspace:update_profile' id=request.session.user_id %}">Edit Your Account!</a></li>
            <li><a href="{% url 'soundspace:user' id=request.session.user_id %}">Your Profile Page!</a></li>
          </ul>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <!-- <a href='{% url 'upload:index' %}'><button class="navbar-right">Uploads</button></a> -->
          <form class="navbar-form navbar-right" action='{% url 'soundspace:logout' %}' method='POST'>
            {% csrf_token %}
            <!-- <div class="form-group"> -->
              <!-- <input type="text" placeholder="Email" class="form-control"> -->
            <!-- </div> -->
            <!-- <div class="form-group"> -->
              <!-- <input type="password" placeholder="Password" class="form-control"> -->
            <!-- </div> -->
            <button type="submit" class="btn btn-success">Sign Out</button>
          </form>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <center>
        {% if messages %}
          {% for message in messages %}
            {{message}}
          {% endfor %}
        {% endif %}
        <h2>Upload to SoundSpace</h2>
        (Tags must be separated by a comma)
        <form class="" action="{% url 'upload:create' %}" enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {{docForm.as_p}}
          <input type="submit" name="upload" value="Upload a Song!">
        </form
      </center>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">

       </div>
        <div class="col-md-4">

        </div>
      </div>

      <hr>

      <footer>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'soundcloud/js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'soundcloud/js/bootstrap.min.js'%}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'soundcloud/js/ie10-viewport-bug-workaround.js'%}"></script>
  </body>
</html>